spring.application.name=ticket

spring.datasource.url=jdbc:postgresql://localhost:5432/db_ticket
spring.datasource.username=postgres
spring.datasource.password=96612.Wil!
spring.jpa.hibernate.ddl-auto=update

